### ISSUE TITLE
选择模板图片可以修改和移动内容是什么插件

### ISSUE THREAD

**Issue by Niofh** [luosijie/Front-end-Blog#1]

**Comment by luosijie** [comment]
这个是自己写的 在main.js里面

**Comment by Niofh** [comment]
这个思路怎么实现的？ @luosijie

**Comment by luosijie** [comment]
就是
1.将鼠标点击的对象存储到 selectedElement 变量上
2.所有的移动、旋转、和生成变换框都基于 selectedElement

不知道你是不是问这个

**Comment by Niofh** [comment]
@luosijie  修改文字也基于这个的吗？

**Comment by luosijie** [comment]
是的
